language: julia
os:
  - linux
dist: bionic
julia:
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
git:
  depth: 99999999

sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -y gfortran-8
  - sudo ln -s /usr/bin/gfortran-8 /usr/local/bin/gfortran
addons:
  apt: 
    packages:
    - hdf5-tools
    - python3
    - python3-matplotlib
    - python3-setuptools
    - python3-pip
install:
  - pip3 install wheel
  - pip3 install camb
env:
  global:
    - PYTHON=python3
    - JULIA_FFTW_PROVIDER=MKL
