version: "3"

services:
  cmblensing:
    image: marius311/cmblensing.jl:mybinder-${TAG:-latest}
    build: 
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - "./docs/Project.toml:/home/cosmo/CMBLensing/docs/Project.toml"
      - "./docs/src:/home/cosmo/CMBLensing/docs/src"
    ports: 
     - "${PORT:-8888}:${PORT:-8888}"
    hostname: localhost
    environment:
     - PORT=${PORT:-8888}
